{% set name = "ipympl" %}
{% set version = "0.5.7" %}
{% set sha256 = "a5e7e8bdc5e97e6397b8507cbbea01c711f770eba903ea87bb5b00bbf4525a32" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - jupyter
    - pip
  run:
    - python
    - ipywidgets >=7.5.0,<8.0
    - ipykernel >=4.7
    - matplotlib >=2.2.0
    - six

test:
  imports:
    - {{ name }}

about:
  home: https://github.com/matplotlib/jupyter-matplotlib
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Matplotlib Jupyter Extension
